### ISSUE TITLE
Omit global options for subcommand

### ISSUE THREAD

**Issue by jdemilledt** [hroptatyr/yuck#12]
Is there any way to omit global options for a subcommand?

**Comment by hroptatyr** [comment]
Emphasis on *a* subcommand?  As in there should be global options and they should be used for all but one subcommand?

Also, -h|--help and -V|--version will always be there.

**Comment by jdemilledt** [comment]
Yes, that is correct

**Comment by hroptatyr** [comment]
Not really, but inside the subcommand switch you could check if any of the options were used.  However, they will be shown in the help output because that's somewhat modular, first show global options then the subcommand sepcific options.

**Comment by jdemilledt** [comment]
Ok, that's fine. I see you have an option `--no-auto-flags` that excludes -h|--help and -V|--version. Could you make an option to exclude -V|--version only? I would implement that, but the source code is far more advanced than I've ever dealt with

**Comment by hroptatyr** [comment]
Sure, that's easy: commit 16cf0db has the --no-auto-flags split into --no-auto-help and --no-auto-version  (and for backward compatibility the --no-auto-flags)

I hope saying the code is advanced doesn't secretly mean it's a mess? :)

**Comment by jdemilledt** [comment]
@hroptatyr It's too advanced for me to tell if it's spaghetti code or not. I honestly don't care if it's a mess. It works amazingly.
