### ISSUE TITLE
No LICENSE/COPYING file

### ISSUE THREAD

**Issue by kravemir** [hroptatyr/yuck#16]
It's a standard to include `LICENSE` or `COPYING` file to indicate users about LICENSE of the project. From README it looks like it's using `BSD 3-clause licence`, but it's good practice to explicitly state it in separate file called `LICENSE` or `COPYING`.

Also, list item `BSD 3-clause licence` pointing at some license, isn't a clear legal statement about project licensing. It's more like a mention, that `BSD 3-clause licence` exists. It doesn't mean, that project is licensed under `BSD 3-clause licence`.

In order not to worry about possible legal issues in future, I would pick only libraries with explicit statement about licensing.

**Comment by joshuakraemer** [comment]
I would also appreciate a dedicated license file. The BSD 3-clause license requires binary distributions to include the license:

> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

This means a license file must be added by binary package maintainers if you do not already provide it.

**Comment by kravemir** [comment]
Closing, it was addressed.

**Comment by opello** [comment]
Conventionally this file is `LICENSE` (ends in `SE`) not `LICENCE` (ends in `CE`).
