### ISSUE TITLE
Is it posible cross compile yuck for arm

### ISSUE THREAD

**Issue by zzs213** [hroptatyr/yuck#17]

**Comment by hroptatyr** [comment]
Hi there,
are you stressing the *cross* compiling bit?  It's certainly possible to build yuck on an ARM box provided that box got a working `m4` macro processor.

That being said, I'm not sure if the target's m4 processor is picked up with the configuration script as is.  But you're always free to edit the `YUCK_M4` define in `src/config.h` after configure'ing.
