### ISSUE TITLE
keep indent in option description

### ISSUE THREAD

**Issue by zzs213** [hroptatyr/yuck#18]
I write the flowwing patch to keep indent in option description:

[0001-keep-indent-in-option-description.patch.txt](https://github.com/hroptatyr/yuck/files/3219370/0001-keep-indent-in-option-description.patch.txt)

**Comment by hroptatyr** [comment]
Hey,

thanks for this contribution. can you check 354a1656 (master) to see if this would do what you were trying to accomplish?  I added a new command line flag -p|--preserve to activate the behaviour.

Also I merged both patches (this and the one from issue #19).

**Comment by zzs213** [comment]
Yeah, It works for me
