### ISSUE TITLE
Can not create multiple subcommands

### ISSUE THREAD

**Issue by czlars** [hroptatyr/yuck#6]
My yuck file tries to define two subcommands:

Usage: rrcsctl
Lists available subcommands.

Usage: rrcsctl zone [zone]
Zone operations

  -l, --list			list all zones
  -k, --kill=zone			kill zone
 
 Usage: rrcsctl shm
 Shared Memory operations
 
  -s, --stats		show statistics

However, the generated yucc file merges the shm and zone commands together:

$ ./rrcsctl -h
Usage: rrcsctl [OPTION]... COMMAND

Lists available subcommands.

COMMAND may be one of:
  zone        Zone operations

Options accepted by all commands:
  -h, --help            display this help and exit
  -V, --version         output version information and exit

$ ./rrcsctl zone -h
Usage: rrcsctl zone [OPTION]... [zone]

Zone operations

Common options:
  -h, --help            display this help and exit
  -V, --version         output version information and exit

Command-specific options:
  -l, --list            list all zones
  -k, --kill=zone       kill zone
                        Usage: rrcsctl shm
                        Shared Memory operations
  -s, --stats           show statistics

Latest yuck version:
$ yuck/src/yuck -V
yuck 0.2.0.git53.c27c78c

What am I doing wrong?

Thanks.

**Comment by hroptatyr** [comment]
The first Usage line should read


    Usage: rrcsctl COMMAND


to turn on the subcommand mode.

**Comment by czlars** [comment]
Hello,

thanks for your reply. Changing the first did not work either (and actually it does not follow the documentation example with the xmpl command), but the problem was caused by accidental leading space in the second subcommand definition.

Thanks,
Jiri

**Comment by hroptatyr** [comment]
Ah, sorry I misread the output.
